version: "3.9"

services:

  server:

    build: ./server

    restart: always

    ports:
      - 3001:3001

    volumes:
      - ./server/grannyLida.db:/app/server/grannyLida.db
      - ./Catalog:/app/Catalog

  client:

    build: ./client

    restart: always

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./Catalog:/usr/share/nginx/Catalog
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - server

  certbot:

    image: certbot/certbot

    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    command: certonly --webroot -w /var/www/certbot --force-renewal --email broke1@yandex.ru -d grannylida.ru -d www.grannylida.ru --agree-tos

    depends_on:
      - client

  

   