version: "3.9"

services:

  server:

    build: /server

    restart: always

    ports:
      - 3001:3001

    volumes:
      - ./server/grannyLida.db:/app/server/grannyLida.db
      - ./Catalog:/app/Catalog

  client:

    build: /client

    restart: always

    ports:
      - 8080:80

    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./Catalog:/usr/share/nginx/Catalog

    depends_on:
      - server